### ISSUE TITLE
Unraveling breaks up sections

### ISSUE THREAD

**Issue by roesech** [BlueBrain/NeuroR#103]
I tried to unravel the morphology of L23_PC_cADpyr_229_2 from the [Blue Brain-database](https://bbp.epfl.ch/nmc-portal/downloads.html) but the sections seem to get scattered in the x-direction.

![](https://user-images.githubusercontent.com/104775520/166249309-296d7de0-aa1d-4660-b581-afdad3a1d227.png)

```python
import matplotlib.pyplot as plt

from morphio import Morphology
from neuror.unravel import unravel


def display(morph, color):
    for sec in morph.sections:
        x = sec.points.T
        plt.plot(x[0], x[1], x[2], c=color)


u, _ = unravel('data/morph_7.h5')
u.write('data/morph_7_unr.h5')

plt.subplot(projection='3d')
display(Morphology('data/morph_7.h5'), 'k')
display(Morphology('data/morph_7_unr.h5'), 'tab:blue')
plt.show()
```

**Comment by arnaudon** [comment]
thanks for reporting, indeed, it looks wrong, I'll take a look in the coming days!

**Comment by arnaudon** [comment]
I just had a look, indeed, you have fallen in a trap and we didn't put a warning;) 
We updated the algorithm recently to use path length window size instead of number of nearby points, to ensure the unraveling is consistent regardless of point sampling along the branches. But I didn't think that if points are further away than the windows size (8 in the default), then the code will break as ugly as you saw. It is not so simple too fix in the unravel itself, but easy to fix with a little pre-processing step, using https://github.com/BlueBrain/morph-tool/blob/master/morph_tool/resampling.py#L175.  I made the code crash if this happens here: https://github.com/BlueBrain/NeuroR/pull/104
The morphology you used was done prior to these updates and was already unravelled with the old version of the code. If you resample first, you will see that the unravel does very little to the morphology.

I hope this can unblock you! Have fun!

**Comment by roesech** [comment]
Thanks! Is there any way to tell if a morphology is already unraveled / repaired / cloned?

**Comment by arnaudon** [comment]
this is internal to bbp (are you working at bbp?) From the name of the morphology form this folder, it is a cloned one (you see dend-[something]-axon-[something], so it has dendrites and axons from different cells. But normally, the released cells from bbp used in a circuit have been unravlled/repaired.

**Comment by roesech** [comment]
Thanks! Is there any way to tell if a morphology is already unraveled / repaired / cloned?
